[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
ignore_missing_imports = True

[mypy-pylss.*]
ignore_missing_imports = False

[mypy-PyQt6.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True
