# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'automaticelutionwindowstretching.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AutomaticElutionWindowStretching(object):
    def setupUi(self, AutomaticElutionWindowStretching):
        AutomaticElutionWindowStretching.setObjectName("AutomaticElutionWindowStretching")
        AutomaticElutionWindowStretching.resize(658, 251)
        self.gridLayout = QtWidgets.QGridLayout(AutomaticElutionWindowStretching)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.calculateButton = QtWidgets.QPushButton(AutomaticElutionWindowStretching)
        self.calculateButton.setMaximumSize(QtCore.QSize(110, 32))
        self.calculateButton.setObjectName("calculateButton")
        self.horizontalLayout_3.addWidget(self.calculateButton)
        spacerItem = QtWidgets.QSpacerItem(796, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(932, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(AutomaticElutionWindowStretching)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.modelBox = QtWidgets.QComboBox(AutomaticElutionWindowStretching)
        self.modelBox.setObjectName("modelBox")
        self.horizontalLayout.addWidget(self.modelBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AutomaticElutionWindowStretching)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(AutomaticElutionWindowStretching)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.tr_min = QtWidgets.QDoubleSpinBox(AutomaticElutionWindowStretching)
        self.tr_min.setDecimals(2)
        self.tr_min.setMinimum(0.0)
        self.tr_min.setMaximum(999999999.0)
        self.tr_min.setProperty("value", 2.0)
        self.tr_min.setObjectName("tr_min")
        self.horizontalLayout_5.addWidget(self.tr_min)
        self.label_5 = QtWidgets.QLabel(AutomaticElutionWindowStretching)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.tr_max = QtWidgets.QDoubleSpinBox(AutomaticElutionWindowStretching)
        self.tr_max.setDecimals(2)
        self.tr_max.setMaximum(999999999.0)
        self.tr_max.setProperty("value", 10.0)
        self.tr_max.setObjectName("tr_max")
        self.horizontalLayout_5.addWidget(self.tr_max)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 2)
        self.closeButton = QtWidgets.QPushButton(AutomaticElutionWindowStretching)
        self.closeButton.setMaximumSize(QtCore.QSize(110, 32))
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 4, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(215, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(AutomaticElutionWindowStretching)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(AutomaticElutionWindowStretching)
        self.doubleSpinBox_6.setReadOnly(True)
        self.doubleSpinBox_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_6)
        self.label_17 = QtWidgets.QLabel(AutomaticElutionWindowStretching)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(AutomaticElutionWindowStretching)
        self.doubleSpinBox_7.setReadOnly(True)
        self.doubleSpinBox_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_7)
        self.label_18 = QtWidgets.QLabel(AutomaticElutionWindowStretching)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(AutomaticElutionWindowStretching)
        self.doubleSpinBox_8.setReadOnly(True)
        self.doubleSpinBox_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_8)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 4)
        self.closeButton.raise_()

        self.retranslateUi(AutomaticElutionWindowStretching)
        QtCore.QMetaObject.connectSlotsByName(AutomaticElutionWindowStretching)

    def retranslateUi(self, AutomaticElutionWindowStretching):
        _translate = QtCore.QCoreApplication.translate
        AutomaticElutionWindowStretching.setWindowTitle(_translate("AutomaticElutionWindowStretching", "Automatic elution windows stretching"))
        self.calculateButton.setText(_translate("AutomaticElutionWindowStretching", "Calculate"))
        self.label_4.setText(_translate("AutomaticElutionWindowStretching", "Select model"))
        self.label.setText(_translate("AutomaticElutionWindowStretching", "Peak window"))
        self.label_3.setText(_translate("AutomaticElutionWindowStretching", "<html><head/><body><p>t<span style=\" vertical-align:sub;\">R</span> min</p></body></html>"))
        self.label_5.setText(_translate("AutomaticElutionWindowStretching", "<html><head/><body><p>t<span style=\" vertical-align:sub;\">R</span> max</p></body></html>"))
        self.closeButton.setText(_translate("AutomaticElutionWindowStretching", "Close"))
        self.label_16.setText(_translate("AutomaticElutionWindowStretching", "Gradient Start:"))
        self.label_17.setText(_translate("AutomaticElutionWindowStretching", "Gradient Stop:"))
        self.label_18.setText(_translate("AutomaticElutionWindowStretching", "Time Gradient:"))

