# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chromanalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChromAnalyzer(object):
    def setupUi(self, ChromAnalyzer):
        ChromAnalyzer.setObjectName("ChromAnalyzer")
        ChromAnalyzer.resize(948, 674)
        self.gridLayout_4 = QtWidgets.QGridLayout(ChromAnalyzer)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(ChromAnalyzer)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.openChromButton = QtWidgets.QPushButton(self.splitter)
        self.openChromButton.setMaximumSize(QtCore.QSize(180, 32))
        self.openChromButton.setObjectName("openChromButton")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 6)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(ChromAnalyzer)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.peakthreshold = QtWidgets.QDoubleSpinBox(ChromAnalyzer)
        self.peakthreshold.setMaximumSize(QtCore.QSize(67, 24))
        self.peakthreshold.setDecimals(4)
        self.peakthreshold.setMinimum(0.0001)
        self.peakthreshold.setSingleStep(0.01)
        self.peakthreshold.setProperty("value", 0.2)
        self.peakthreshold.setObjectName("peakthreshold")
        self.gridLayout_3.addWidget(self.peakthreshold, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(ChromAnalyzer)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.leftpoints = QtWidgets.QSpinBox(ChromAnalyzer)
        self.leftpoints.setObjectName("leftpoints")
        self.gridLayout_3.addWidget(self.leftpoints, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 2, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(ChromAnalyzer)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.windowsize = QtWidgets.QSpinBox(ChromAnalyzer)
        self.windowsize.setMinimum(3)
        self.windowsize.setMaximum(9999999)
        self.windowsize.setProperty("value", 5)
        self.windowsize.setObjectName("windowsize")
        self.gridLayout_2.addWidget(self.windowsize, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(ChromAnalyzer)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.rightpoints = QtWidgets.QSpinBox(ChromAnalyzer)
        self.rightpoints.setObjectName("rightpoints")
        self.gridLayout_2.addWidget(self.rightpoints, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 2, 2, 2)
        spacerItem = QtWidgets.QSpacerItem(380, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 4, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(377, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 4, 1, 2)
        self.analyzeButton = QtWidgets.QPushButton(ChromAnalyzer)
        self.analyzeButton.setMaximumSize(QtCore.QSize(130, 32))
        self.analyzeButton.setObjectName("analyzeButton")
        self.gridLayout_4.addWidget(self.analyzeButton, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(509, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 3, 1, 1, 5)
        self.tableBox = QtWidgets.QGroupBox(ChromAnalyzer)
        self.tableBox.setObjectName("tableBox")
        self.gridLayout = QtWidgets.QGridLayout(self.tableBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.tableBox)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.tableBox, 4, 0, 1, 3)
        self.plotterBox = QtWidgets.QGroupBox(ChromAnalyzer)
        self.plotterBox.setMinimumSize(QtCore.QSize(481, 371))
        self.plotterBox.setObjectName("plotterBox")
        self.gridLayout_4.addWidget(self.plotterBox, 4, 3, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(376, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 5, 0, 1, 3)
        self.aboutButton = QtWidgets.QPushButton(ChromAnalyzer)
        self.aboutButton.setObjectName("aboutButton")
        self.gridLayout_4.addWidget(self.aboutButton, 5, 4, 1, 1)
        self.quitButton = QtWidgets.QPushButton(ChromAnalyzer)
        self.quitButton.setObjectName("quitButton")
        self.gridLayout_4.addWidget(self.quitButton, 5, 5, 1, 1)

        self.retranslateUi(ChromAnalyzer)
        QtCore.QMetaObject.connectSlotsByName(ChromAnalyzer)

    def retranslateUi(self, ChromAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        ChromAnalyzer.setWindowTitle(_translate("ChromAnalyzer", "ChromAnalyzer"))
        self.openChromButton.setText(_translate("ChromAnalyzer", "Open Chromatogram"))
        self.label.setText(_translate("ChromAnalyzer", "Peak threshold"))
        self.label_3.setText(_translate("ChromAnalyzer", "Additional left points"))
        self.label_2.setText(_translate("ChromAnalyzer", "Window size"))
        self.label_4.setText(_translate("ChromAnalyzer", "Additional right points"))
        self.analyzeButton.setText(_translate("ChromAnalyzer", "Analyze"))
        self.tableBox.setTitle(_translate("ChromAnalyzer", "Peak results"))
        self.plotterBox.setTitle(_translate("ChromAnalyzer", "Chromatogram viewer"))
        self.aboutButton.setText(_translate("ChromAnalyzer", "About"))
        self.quitButton.setText(_translate("ChromAnalyzer", "Quit"))

