# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importdialog.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImportDialog(object):
    def setupUi(self, ImportDialog):
        ImportDialog.setObjectName("ImportDialog")
        ImportDialog.resize(493, 575)
        self.gridLayout_3 = QtWidgets.QGridLayout(ImportDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitlineby = QtWidgets.QComboBox(ImportDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitlineby.sizePolicy().hasHeightForWidth())
        self.splitlineby.setSizePolicy(sizePolicy)
        self.splitlineby.setMinimumSize(QtCore.QSize(0, 23))
        self.splitlineby.setMaximumSize(QtCore.QSize(112, 23))
        self.splitlineby.setEditable(True)
        self.splitlineby.setObjectName("splitlineby")
        self.splitlineby.addItem("")
        self.splitlineby.addItem("")
        self.splitlineby.addItem("")
        self.splitlineby.addItem("")
        self.splitlineby.addItem("")
        self.gridLayout_3.addWidget(self.splitlineby, 4, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(ImportDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 23))
        self.label_4.setMaximumSize(QtCore.QSize(159, 23))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 2, 1)
        self.line = QtWidgets.QFrame(ImportDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 2, 0, 1, 3)
        self.okButton = QtWidgets.QPushButton(ImportDialog)
        self.okButton.setMaximumSize(QtCore.QSize(110, 32))
        self.okButton.setObjectName("okButton")
        self.gridLayout_3.addWidget(self.okButton, 7, 2, 1, 1)
        self.closeButton = QtWidgets.QPushButton(ImportDialog)
        self.closeButton.setMaximumSize(QtCore.QSize(110, 32))
        self.closeButton.setObjectName("closeButton")
        self.gridLayout_3.addWidget(self.closeButton, 7, 1, 1, 1)
        self.firstcolobjname = QtWidgets.QCheckBox(ImportDialog)
        self.firstcolobjname.setMinimumSize(QtCore.QSize(0, 21))
        self.firstcolobjname.setMaximumSize(QtCore.QSize(16777215, 21))
        self.firstcolobjname.setObjectName("firstcolobjname")
        self.gridLayout_3.addWidget(self.firstcolobjname, 5, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(ImportDialog)
        self.tableView.setMinimumSize(QtCore.QSize(50, 50))
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 6, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(305, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 7, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.openButton = QtWidgets.QPushButton(ImportDialog)
        self.openButton.setMaximumSize(QtCore.QSize(110, 32))
        self.openButton.setObjectName("openButton")
        self.gridLayout_2.addWidget(self.openButton, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(ImportDialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.splitter, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(ImportDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(ImportDialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(ImportDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dwelVolSpinBox = QtWidgets.QDoubleSpinBox(ImportDialog)
        self.dwelVolSpinBox.setDecimals(3)
        self.dwelVolSpinBox.setMinimum(0.0)
        self.dwelVolSpinBox.setProperty("value", 0.0)
        self.dwelVolSpinBox.setObjectName("dwelVolSpinBox")
        self.gridLayout.addWidget(self.dwelVolSpinBox, 0, 1, 1, 1)
        self.flowrateSpinBox = QtWidgets.QDoubleSpinBox(ImportDialog)
        self.flowrateSpinBox.setDecimals(3)
        self.flowrateSpinBox.setProperty("value", 0.0)
        self.flowrateSpinBox.setObjectName("flowrateSpinBox")
        self.gridLayout.addWidget(self.flowrateSpinBox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(ImportDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.t0SpinBox = QtWidgets.QDoubleSpinBox(ImportDialog)
        self.t0SpinBox.setDecimals(3)
        self.t0SpinBox.setProperty("value", 0.0)
        self.t0SpinBox.setObjectName("t0SpinBox")
        self.gridLayout.addWidget(self.t0SpinBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(ImportDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 3)

        self.retranslateUi(ImportDialog)
        QtCore.QMetaObject.connectSlotsByName(ImportDialog)

    def retranslateUi(self, ImportDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportDialog.setWindowTitle(_translate("ImportDialog", "Import retention data"))
        self.splitlineby.setItemText(0, _translate("ImportDialog", ";"))
        self.splitlineby.setItemText(1, _translate("ImportDialog", "TAB"))
        self.splitlineby.setItemText(2, _translate("ImportDialog", "SPACE"))
        self.splitlineby.setItemText(3, _translate("ImportDialog", ","))
        self.splitlineby.setItemText(4, _translate("ImportDialog", "<CUSTOM>"))
        self.label_4.setText(_translate("ImportDialog", "Separator:"))
        self.okButton.setText(_translate("ImportDialog", "OK"))
        self.closeButton.setText(_translate("ImportDialog", "Close"))
        self.firstcolobjname.setText(_translate("ImportDialog", "First columns contain object names"))
        self.openButton.setText(_translate("ImportDialog", "Open"))
        self.label_7.setText(_translate("ImportDialog", "File name"))
        self.label_3.setText(_translate("ImportDialog", "Flow rate:"))
        self.label_2.setText(_translate("ImportDialog", "t0:"))
        self.label.setText(_translate("ImportDialog", "Dwell Volume:"))

