# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(292, 60))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.zoomButton = QtWidgets.QPushButton(self.groupBox)
        self.zoomButton.setMinimumSize(QtCore.QSize(90, 32))
        self.zoomButton.setMaximumSize(QtCore.QSize(90, 32))
        self.zoomButton.setObjectName("zoomButton")
        self.gridLayout_7.addWidget(self.zoomButton, 0, 0, 1, 1)
        self.panButton = QtWidgets.QPushButton(self.groupBox)
        self.panButton.setMinimumSize(QtCore.QSize(90, 32))
        self.panButton.setMaximumSize(QtCore.QSize(90, 32))
        self.panButton.setObjectName("panButton")
        self.gridLayout_7.addWidget(self.panButton, 0, 1, 1, 1)
        self.rescaleButton = QtWidgets.QPushButton(self.groupBox)
        self.rescaleButton.setMinimumSize(QtCore.QSize(90, 32))
        self.rescaleButton.setMaximumSize(QtCore.QSize(90, 32))
        self.rescaleButton.setObjectName("rescaleButton")
        self.gridLayout_7.addWidget(self.rescaleButton, 0, 2, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 0, 1, 1, 1)
        self.plotterBox = QtWidgets.QGroupBox(self.centralwidget)
        self.plotterBox.setMinimumSize(QtCore.QSize(680, 350))
        self.plotterBox.setObjectName("plotterBox")
        self.gridLayout_11.addWidget(self.plotterBox, 1, 1, 1, 2)
        self.settingBox = QtWidgets.QGroupBox(self.centralwidget)
        self.settingBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.settingBox.setObjectName("settingBox")
        self.gridLayout = QtWidgets.QGridLayout(self.settingBox)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(self.settingBox)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 240, 558))
        self.page.setObjectName("page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.addButton = QtWidgets.QPushButton(self.page)
        self.addButton.setObjectName("addButton")
        self.gridLayout_8.addWidget(self.addButton, 0, 0, 1, 1)
        self.removeButton = QtWidgets.QPushButton(self.page)
        self.removeButton.setObjectName("removeButton")
        self.gridLayout_8.addWidget(self.removeButton, 0, 1, 1, 1)
        self.listView = QtWidgets.QListView(self.page)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName("listView")
        self.gridLayout_8.addWidget(self.listView, 1, 0, 1, 2)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 240, 558))
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.ColumnPorositySpinBox = QtWidgets.QDoubleSpinBox(self.page_2)
        self.ColumnPorositySpinBox.setDecimals(2)
        self.ColumnPorositySpinBox.setProperty("value", 1.7)
        self.ColumnPorositySpinBox.setObjectName("ColumnPorositySpinBox")
        self.gridLayout_2.addWidget(self.ColumnPorositySpinBox, 2, 1, 1, 1)
        self.ColumnLenghtSpinBox = QtWidgets.QDoubleSpinBox(self.page_2)
        self.ColumnLenghtSpinBox.setDecimals(0)
        self.ColumnLenghtSpinBox.setProperty("value", 15.0)
        self.ColumnLenghtSpinBox.setObjectName("ColumnLenghtSpinBox")
        self.gridLayout_2.addWidget(self.ColumnLenghtSpinBox, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.CulumnDiameterSpinBox = QtWidgets.QDoubleSpinBox(self.page_2)
        self.CulumnDiameterSpinBox.setProperty("value", 2.1)
        self.CulumnDiameterSpinBox.setObjectName("CulumnDiameterSpinBox")
        self.gridLayout_2.addWidget(self.CulumnDiameterSpinBox, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 5, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.modelBox = QtWidgets.QComboBox(self.page_2)
        self.modelBox.setObjectName("modelBox")
        self.gridLayout_6.addWidget(self.modelBox, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 0, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_4.setDecimals(2)
        self.doubleSpinBox_4.setMinimum(1.0)
        self.doubleSpinBox_4.setMaximum(200.0)
        self.doubleSpinBox_4.setProperty("value", 10.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_9.addWidget(self.doubleSpinBox_4, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_9, 4, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_5.setDecimals(3)
        self.doubleSpinBox_5.setMinimum(0.001)
        self.doubleSpinBox_5.setSingleStep(0.05)
        self.doubleSpinBox_5.setProperty("value", 0.37)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_5)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 6, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_2.setMaximum(100.0)
        self.doubleSpinBox_2.setProperty("value", 5.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_2, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_3.setMaximum(100.0)
        self.doubleSpinBox_3.setProperty("value", 95.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_3.addWidget(self.doubleSpinBox_3, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_1.setDecimals(3)
        self.doubleSpinBox_1.setMinimum(0.001)
        self.doubleSpinBox_1.setSingleStep(0.05)
        self.doubleSpinBox_1.setProperty("value", 0.3)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.verticalLayout.addWidget(self.doubleSpinBox_1)
        self.gridLayout_5.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.settingBox, 0, 0, 3, 1)
        self.plotterBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.plotterBox_2.setMinimumSize(QtCore.QSize(680, 150))
        self.plotterBox_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.plotterBox_2.setObjectName("plotterBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.plotterBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableView = QtWidgets.QTableView(self.plotterBox_2)
        self.tableView.setObjectName("tableView")
        self.gridLayout_10.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.plotterBox_2, 2, 1, 1, 2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(240, 60))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(9999999, 60))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setOverwriteMode(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_11.addWidget(self.plainTextEdit, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCalculation = QtWidgets.QMenu(self.menubar)
        self.menuCalculation.setObjectName("menuCalculation")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPlot_2 = QtWidgets.QMenu(self.menubar)
        self.menuPlot_2.setObjectName("menuPlot_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCalcLSSParameter = QtWidgets.QAction(MainWindow)
        self.actionCalcLSSParameter.setObjectName("actionCalcLSSParameter")
        self.actionAutomaticElutionWindowStretching = QtWidgets.QAction(MainWindow)
        self.actionAutomaticElutionWindowStretching.setObjectName("actionAutomaticElutionWindowStretching")
        self.actionGetBestIsocraticConditions = QtWidgets.QAction(MainWindow)
        self.actionGetBestIsocraticConditions.setObjectName("actionGetBestIsocraticConditions")
        self.actionOpen_Session = QtWidgets.QAction(MainWindow)
        self.actionOpen_Session.setObjectName("actionOpen_Session")
        self.actionSave_Session = QtWidgets.QAction(MainWindow)
        self.actionSave_Session.setObjectName("actionSave_Session")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTecnical_Support = QtWidgets.QAction(MainWindow)
        self.actionTecnical_Support.setObjectName("actionTecnical_Support")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionExport_LSS_Parameter = QtWidgets.QAction(MainWindow)
        self.actionExport_LSS_Parameter.setObjectName("actionExport_LSS_Parameter")
        self.actionSelectivityMap = QtWidgets.QAction(MainWindow)
        self.actionSelectivityMap.setObjectName("actionSelectivityMap")
        self.actionResolutionMap = QtWidgets.QAction(MainWindow)
        self.actionResolutionMap.setObjectName("actionResolutionMap")
        self.menuFile.addAction(self.actionQuit)
        self.menuCalculation.addAction(self.actionCalcLSSParameter)
        self.menuCalculation.addSeparator()
        self.menuCalculation.addAction(self.actionAutomaticElutionWindowStretching)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionTecnical_Support)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuPlot_2.addAction(self.actionSelectivityMap)
        self.menuPlot_2.addAction(self.actionResolutionMap)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCalculation.menuAction())
        self.menubar.addAction(self.menuPlot_2.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyLSS"))
        self.groupBox.setTitle(_translate("MainWindow", "Plot options"))
        self.zoomButton.setText(_translate("MainWindow", "Zoom"))
        self.panButton.setText(_translate("MainWindow", "Pan"))
        self.rescaleButton.setText(_translate("MainWindow", "Rescale"))
        self.plotterBox.setTitle(_translate("MainWindow", "Chromatogram"))
        self.settingBox.setTitle(_translate("MainWindow", "Settings"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.removeButton.setText(_translate("MainWindow", "Remove"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Data input"))
        self.label_9.setText(_translate("MainWindow", "cm"))
        self.label_10.setText(_translate("MainWindow", "mm"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>µm</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Column length"))
        self.label_8.setText(_translate("MainWindow", "Particle size"))
        self.label_7.setText(_translate("MainWindow", "Column diameter"))
        self.label_5.setText(_translate("MainWindow", "Select LSS model.."))
        self.label_6.setText(_translate("MainWindow", "Gradient time"))
        self.label_14.setText(_translate("MainWindow", "Dwell volume"))
        self.label_2.setText(_translate("MainWindow", "Gradient Start"))
        self.label_3.setText(_translate("MainWindow", "Gradient End"))
        self.label.setText(_translate("MainWindow", "Flow Rate"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Gradient Parameters"))
        self.plotterBox_2.setTitle(_translate("MainWindow", "Data"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Critical resolution: 1.80\n"
"Molecules: \n"
"  - A\n"
"  - B"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCalculation.setTitle(_translate("MainWindow", "Calculation"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuPlot_2.setTitle(_translate("MainWindow", "Plot"))
        self.actionCalcLSSParameter.setText(_translate("MainWindow", "Calculate LSS parameter"))
        self.actionAutomaticElutionWindowStretching.setText(_translate("MainWindow", "Automatic elution window stretching"))
        self.actionGetBestIsocraticConditions.setText(_translate("MainWindow", "Get best isocratic conditions"))
        self.actionOpen_Session.setText(_translate("MainWindow", "Open Session"))
        self.actionSave_Session.setText(_translate("MainWindow", "Save Session"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionTecnical_Support.setText(_translate("MainWindow", "Tecnical Support"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionExport_LSS_Parameter.setText(_translate("MainWindow", "Export LSS Parameter"))
        self.actionSelectivityMap.setText(_translate("MainWindow", "Selectivity Map"))
        self.actionResolutionMap.setText(_translate("MainWindow", "Resolution Map"))

