# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(990, 720)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_11 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(292, 60))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.zoomButton = QtGui.QPushButton(self.groupBox)
        self.zoomButton.setMinimumSize(QtCore.QSize(90, 32))
        self.zoomButton.setMaximumSize(QtCore.QSize(90, 32))
        self.zoomButton.setObjectName(_fromUtf8("zoomButton"))
        self.gridLayout_7.addWidget(self.zoomButton, 0, 0, 1, 1)
        self.panButton = QtGui.QPushButton(self.groupBox)
        self.panButton.setMinimumSize(QtCore.QSize(90, 32))
        self.panButton.setMaximumSize(QtCore.QSize(90, 32))
        self.panButton.setObjectName(_fromUtf8("panButton"))
        self.gridLayout_7.addWidget(self.panButton, 0, 1, 1, 1)
        self.rescaleButton = QtGui.QPushButton(self.groupBox)
        self.rescaleButton.setMinimumSize(QtCore.QSize(90, 32))
        self.rescaleButton.setMaximumSize(QtCore.QSize(90, 32))
        self.rescaleButton.setObjectName(_fromUtf8("rescaleButton"))
        self.gridLayout_7.addWidget(self.rescaleButton, 0, 2, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 0, 1, 1, 1)
        self.plotterBox = QtGui.QGroupBox(self.centralwidget)
        self.plotterBox.setMinimumSize(QtCore.QSize(680, 350))
        self.plotterBox.setObjectName(_fromUtf8("plotterBox"))
        self.gridLayout_11.addWidget(self.plotterBox, 1, 1, 1, 2)
        self.settingBox = QtGui.QGroupBox(self.centralwidget)
        self.settingBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.settingBox.setObjectName(_fromUtf8("settingBox"))
        self.gridLayout = QtGui.QGridLayout(self.settingBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolBox = QtGui.QToolBox(self.settingBox)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 240, 558))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.addButton = QtGui.QPushButton(self.page)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.gridLayout_8.addWidget(self.addButton, 0, 0, 1, 1)
        self.removeButton = QtGui.QPushButton(self.page)
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.gridLayout_8.addWidget(self.removeButton, 0, 1, 1, 1)
        self.listView = QtGui.QListView(self.page)
        self.listView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout_8.addWidget(self.listView, 1, 0, 1, 2)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 240, 558))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.ColumnPorositySpinBox = QtGui.QDoubleSpinBox(self.page_2)
        self.ColumnPorositySpinBox.setDecimals(2)
        self.ColumnPorositySpinBox.setProperty("value", 1.7)
        self.ColumnPorositySpinBox.setObjectName(_fromUtf8("ColumnPorositySpinBox"))
        self.gridLayout_2.addWidget(self.ColumnPorositySpinBox, 2, 1, 1, 1)
        self.ColumnLenghtSpinBox = QtGui.QDoubleSpinBox(self.page_2)
        self.ColumnLenghtSpinBox.setDecimals(0)
        self.ColumnLenghtSpinBox.setProperty("value", 15.0)
        self.ColumnLenghtSpinBox.setObjectName(_fromUtf8("ColumnLenghtSpinBox"))
        self.gridLayout_2.addWidget(self.ColumnLenghtSpinBox, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.CulumnDiameterSpinBox = QtGui.QDoubleSpinBox(self.page_2)
        self.CulumnDiameterSpinBox.setProperty("value", 2.1)
        self.CulumnDiameterSpinBox.setObjectName(_fromUtf8("CulumnDiameterSpinBox"))
        self.gridLayout_2.addWidget(self.CulumnDiameterSpinBox, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 5, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.modelBox = QtGui.QComboBox(self.page_2)
        self.modelBox.setObjectName(_fromUtf8("modelBox"))
        self.gridLayout_6.addWidget(self.modelBox, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_9.addWidget(self.label_6, 0, 0, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_4.setDecimals(2)
        self.doubleSpinBox_4.setMinimum(1.0)
        self.doubleSpinBox_4.setMaximum(200.0)
        self.doubleSpinBox_4.setProperty("value", 10.0)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout_9.addWidget(self.doubleSpinBox_4, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_9, 4, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_14 = QtGui.QLabel(self.page_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_2.addWidget(self.label_14)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_5.setDecimals(3)
        self.doubleSpinBox_5.setMinimum(0.001)
        self.doubleSpinBox_5.setSingleStep(0.05)
        self.doubleSpinBox_5.setProperty("value", 0.37)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.verticalLayout_2.addWidget(self.doubleSpinBox_5)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 6, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.page_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_2.setMaximum(100.0)
        self.doubleSpinBox_2.setProperty("value", 5.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_2, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.page_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_3.setMaximum(100.0)
        self.doubleSpinBox_3.setProperty("value", 95.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_3, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.page_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.doubleSpinBox_1 = QtGui.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_1.setDecimals(3)
        self.doubleSpinBox_1.setMinimum(0.001)
        self.doubleSpinBox_1.setSingleStep(0.05)
        self.doubleSpinBox_1.setProperty("value", 0.3)
        self.doubleSpinBox_1.setObjectName(_fromUtf8("doubleSpinBox_1"))
        self.verticalLayout.addWidget(self.doubleSpinBox_1)
        self.gridLayout_5.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.settingBox, 0, 0, 3, 1)
        self.plotterBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.plotterBox_2.setMinimumSize(QtCore.QSize(680, 150))
        self.plotterBox_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.plotterBox_2.setObjectName(_fromUtf8("plotterBox_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.plotterBox_2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tableView = QtGui.QTableView(self.plotterBox_2)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_10.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.plotterBox_2, 2, 1, 1, 2)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(240, 60))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(9999999, 60))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setOverwriteMode(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_11.addWidget(self.plainTextEdit, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuCalculation = QtGui.QMenu(self.menubar)
        self.menuCalculation.setObjectName(_fromUtf8("menuCalculation"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuPlot_2 = QtGui.QMenu(self.menubar)
        self.menuPlot_2.setObjectName(_fromUtf8("menuPlot_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionCalcLSSParameter = QtGui.QAction(MainWindow)
        self.actionCalcLSSParameter.setObjectName(_fromUtf8("actionCalcLSSParameter"))
        self.actionGetBestGradientConditions = QtGui.QAction(MainWindow)
        self.actionGetBestGradientConditions.setObjectName(_fromUtf8("actionGetBestGradientConditions"))
        self.actionGetBestIsocraticConditions = QtGui.QAction(MainWindow)
        self.actionGetBestIsocraticConditions.setObjectName(_fromUtf8("actionGetBestIsocraticConditions"))
        self.actionOpen_Session = QtGui.QAction(MainWindow)
        self.actionOpen_Session.setObjectName(_fromUtf8("actionOpen_Session"))
        self.actionSave_Session = QtGui.QAction(MainWindow)
        self.actionSave_Session.setObjectName(_fromUtf8("actionSave_Session"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionTecnical_Support = QtGui.QAction(MainWindow)
        self.actionTecnical_Support.setObjectName(_fromUtf8("actionTecnical_Support"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionExport_LSS_Parameter = QtGui.QAction(MainWindow)
        self.actionExport_LSS_Parameter.setObjectName(_fromUtf8("actionExport_LSS_Parameter"))
        self.actionSelectivityMap = QtGui.QAction(MainWindow)
        self.actionSelectivityMap.setObjectName(_fromUtf8("actionSelectivityMap"))
        self.menuFile.addAction(self.actionQuit)
        self.menuCalculation.addAction(self.actionCalcLSSParameter)
        self.menuCalculation.addSeparator()
        self.menuCalculation.addAction(self.actionGetBestGradientConditions)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionTecnical_Support)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuPlot_2.addAction(self.actionSelectivityMap)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCalculation.menuAction())
        self.menubar.addAction(self.menuPlot_2.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyLSS", None))
        self.groupBox.setTitle(_translate("MainWindow", "Plot options", None))
        self.zoomButton.setText(_translate("MainWindow", "Zoom", None))
        self.panButton.setText(_translate("MainWindow", "Pan", None))
        self.rescaleButton.setText(_translate("MainWindow", "Rescale", None))
        self.plotterBox.setTitle(_translate("MainWindow", "Chromatogram", None))
        self.settingBox.setTitle(_translate("MainWindow", "Settings", None))
        self.addButton.setText(_translate("MainWindow", "Add", None))
        self.removeButton.setText(_translate("MainWindow", "Remove", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Data input", None))
        self.label_9.setText(_translate("MainWindow", "cm", None))
        self.label_10.setText(_translate("MainWindow", "mm", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>µm</p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "Column length", None))
        self.label_8.setText(_translate("MainWindow", "Particle size", None))
        self.label_7.setText(_translate("MainWindow", "Column diameter", None))
        self.label_5.setText(_translate("MainWindow", "Select LSS model..", None))
        self.label_6.setText(_translate("MainWindow", "Gradient time", None))
        self.label_14.setText(_translate("MainWindow", "Dwell volume", None))
        self.label_2.setText(_translate("MainWindow", "Gradient Start", None))
        self.label_3.setText(_translate("MainWindow", "Gradient End", None))
        self.label.setText(_translate("MainWindow", "Flow Rate", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Gradient Parameters", None))
        self.plotterBox_2.setTitle(_translate("MainWindow", "Data", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Critical resolution: 1.80\n"
"Molecules: \n"
"  - A\n"
"  - B", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuCalculation.setTitle(_translate("MainWindow", "Calculation", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuPlot_2.setTitle(_translate("MainWindow", "Plot", None))
        self.actionCalcLSSParameter.setText(_translate("MainWindow", "Calculate LSS parameter", None))
        self.actionGetBestGradientConditions.setText(_translate("MainWindow", "Get best gradient conditions", None))
        self.actionGetBestIsocraticConditions.setText(_translate("MainWindow", "Get best isocratic conditions", None))
        self.actionOpen_Session.setText(_translate("MainWindow", "Open Session", None))
        self.actionSave_Session.setText(_translate("MainWindow", "Save Session", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionTecnical_Support.setText(_translate("MainWindow", "Tecnical Support", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))
        self.actionExport_LSS_Parameter.setText(_translate("MainWindow", "Export LSS Parameter", None))
        self.actionSelectivityMap.setText(_translate("MainWindow", "Selectivity Map", None))

