pylss.py : computebestgradient.ui aboutdialog.ui computelss.ui importdialog.ui mainwindow.ui
	pyuic4 aboutdialog.ui -o gui_aboutdialog.py
	pyuic4 computebestgradient.ui -o gui_computebestgradient.py
	pyuic4 computelss.ui -o gui_computelss.py
	pyuic4 importdialog.ui -o gui_importdialog.py
	pyuic4 mainwindow.ui -o mainwindow.py
