pylss.py : plotmaps.ui automaticelutionwindowstretching.ui aboutdialog.ui computelss.ui importdialog.ui mainwindow.ui
	pyuic4 aboutdialog.ui -o gui_aboutdialog.py
	pyuic4 plotmaps.ui -o gui_plotmaps.py
	pyuic4 automaticelutionwindowstretching.ui -o gui_automaticelutionwindowstretching.py
	pyuic4 computelss.ui -o gui_computelss.py
	pyuic4 importdialog.ui -o gui_importdialog.py
	pyuic4 mainwindow.ui -o mainwindow.py
