pylss.py : plotmaps.ui automaticelutionwindowstretching.ui aboutdialog.ui computelss.ui importdialog.ui mainwindow.ui chromanalyzer.ui
	pyuic5 aboutdialog.ui -o gui_aboutdialog.py
	pyuic5 plotmaps.ui -o gui_plotmaps.py
	pyuic5 automaticelutionwindowstretching.ui -o gui_automaticelutionwindowstretching.py
	pyuic5 computelss.ui -o gui_computelss.py
	pyuic5 importdialog.ui -o gui_importdialog.py
	pyuic5 mainwindow.ui -o mainwindow.py
	pyuic5 chromanalyzer.ui -o gui_chromanalyzer.py
